### ISSUE TITLE
include this package in a distro

### ISSUE THREAD

**Issue by sbrun** [kgshank/gse-refresh-wifi#1]
Hi,
I would like to package this extension for the distro kali linux.
But two things are missing to this properly:
1. the license: could you include the license under which this code is provided?
2. a tagged release: could you provide a tagged release, the packaging tools works best with tagged release.
The most important thing is the license.
Thanks

**Comment by kgshank** [comment]
Hi @sbrun ,
Thanks for considering inclusion of my extension in a distro.
I have included the license and release tag. Please verify and let me know if it suits your requirement.

Thanks

**Comment by sbrun** [comment]
Hi,
Everything is ok for me.
Thank you very much
