### ISSUE TITLE
Make compatible with shell 3.28

### ISSUE THREAD

**Issue by tomyo** [kgshank/gse-refresh-wifi#11]
In 3.28, when hitting refresh, no networks appear, ever.

Thanks!

**Comment by kgshank** [comment]
Tested in 3.30 and works without issue.

**Comment by khalid3bdallah** [comment]
I have the same issue
Gnome version: 3.28.4

**Comment by kgshank** [comment]
@Khalid3bdallah  is there any error in journalctl. unfortunately I dont have 3.28 with me to test the extension. which distro are you using, I can test in a vm?

**Comment by khalid3bdallah** [comment]
@kgshank There're no errors in journalctl, I opened `journalctl -f` and  `journalctl -kf` while clicking on the refresh button and nothing appeared in the logs.

I'm using Ubuntu 18.04.3 with kernel 4.15.0-65-generic.

Let me know if you need more info.
Thanks for your consideration

**Comment by kgshank** [comment]
@Khalid3bdallah can you test the version from git. I have updated the compatibility now

**Comment by khalid3bdallah** [comment]
> @Khalid3bdallah can you test the version from git. I have updated the compatibility now

@kgshank I tried the version from git, I noticed that the networks list doesn't disappear when I click on the refresh button, but unfortunately it didn't refresh the list, I tried this while enabling / disabling a hotspot, I believe that the button didn't refresh the networks list
