### ISSUE TITLE
Infinite Reload without any Result (3.30, Ubuntu 18.10) 

### ISSUE THREAD

**Issue by 0unknwn** [kgshank/gse-refresh-wifi#12]
If I press the button nothing happens. Could you fix that? 
(As this should be a very basic function, it's a shame that you need an extensions to have this button! But that's of course not your fault!)

**Comment by F50Ci37Y** [comment]
in 19.04 gnome 3.32 also not work
when click reload write no network

**Comment by kgshank** [comment]
Updated version uploaded. But note that 3.32 does not need the extension, the list is updated every 15 sec
