### ISSUE TITLE
Not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by tiagoFlach** [kgshank/gse-refresh-wifi#14]
The refresh button are not clickable on Gnome 3.36.

I move the mouse over de button, click on it, but nothing happens. When mouse is hover the button, nothing happens too.

![Screenshot 2020-05-07 15-29-34](https://user-images.githubusercontent.com/17373135/81332285-36059700-9079-11ea-8f1d-1e3c45b48f9e.png)

**Comment by kgshank** [comment]
New version uploaded. Also, Gnome 3.36 doesn't need this extension. The list is updated periodically.

**Comment by salim-b** [comment]
> New version uploaded. 

Works fine on Ubuntu 20.04 (GNOME 3.36.2). :+1: 

The "icing on the cake" would be to have some animation/progress indication of the network scan after the button is pressed... :innocent: 

> Also, Gnome 3.36 doesn't need this extension. The list is updated periodically.

Thanks for the info, I didn't know about the improved auto-update interval. But honestly, I still like to have a "manual" button to trigger a re-scan so I don't need to wait (for 15s in the worst case, I know) at all.

**Comment by kgshank** [comment]
> > New version uploaded.
> 
> Works fine on Ubuntu 20.04 (GNOME 3.36.2). 👍
> 
> The "icing on the cake" would be to have some animation/progress indication of the network scan after the button is pressed... 😇
> 

The initial versions of the extension used to have that. It was removed, as it just displays the for a second or so, because the feedback from the device for new scan request is not very reliable and a partial list of wifi networks is returned very quickly. But it takes little more time to show up the new networks. It kind of gave a feel that the network list is not updated properly by the extension.

**Comment by salim-b** [comment]
> The initial versions of the extension used to have that. It was removed, as it just displays the for a second or so, because the feedback from the device for new scan request is not very reliable and a partial list of wifi networks is returned very quickly. But it takes little more time to show up the new networks. It kind of gave a feel that the network list is not updated properly by the extension.

I see. So there's no way for the extension to tell when the WiFi re-scan has finished?

**Comment by kgshank** [comment]
Unfortunately no !!
