### ISSUE TITLE
Not working on Gnome 40

### ISSUE THREAD

**Issue by darylf** [kgshank/gse-refresh-wifi#20]
I recently updated to Fedora 34, which ships with GNOME 40, and the extensions page tells me this extension is "outdated".

I'm not sure what's involved in updating and supporting the latest GNOME, but I love this extension and severely miss it.

I'm not sure if there's anything I can do to help: provide logs or screenshots or anything.

**Comment by wit-inc** [comment]
on arch linux : just add the new gnome-shell version (i.e 40 ) to "shell-version" in _metadata.json_ (.local/share/gnome-shell/extensions/refresh-wifi@kgshank.net
)
or try to install the extension manually

**Comment by paoloantinori** [comment]
Nice, thanks for the workaround! Working on Fedora 34!

**Comment by Shrijalexpo** [comment]
I am using this extension on Ubuntu 21.10 with Gnome version 40
It is giving me an error: The extension is incompatible with the current GNOME version
This extension was working super on previous versions.
Please look at this issue
