### ISSUE TITLE
Retire extension?

### ISSUE THREAD

**Issue by hadess** [kgshank/gse-refresh-wifi#7]
The bug that this extension was supposed to fix is now fixed in https://bugzilla.gnome.org/show_bug.cgi?id=767918 so there is no need to refresh at all.

**Comment by highvoltage** [comment]
Did that patch make it into GNOME 3.22? I just packaged the extension for Debian, but since Debian 9 is shipping with GNOME 3.22 it might be a good idea to remove it again.

**Comment by kgshank** [comment]
The patch has not made into 3.22 yet, it seems to be available in the master 

https://git.gnome.org/browse/gnome-shell/tree/js/ui/status/network.js?h=gnome-3-22
https://git.gnome.org/browse/gnome-shell/snapshot/gnome-shell-3.22.1.tar.xz

**Comment by hadess** [comment]
Let me reopen the bug. At least, we can restrict the extension to older versions of GNOME when that's fixed.

**Comment by highvoltage** [comment]
Yeah keeping support open for distros that run long term support releases (Debian 9, Ubuntu 16.04, RHEL, etc) will be good. So this plugin still has some 5 years of life left before it needs to die :)

**Comment by kgshank** [comment]
The patch has made into 3.22.2, so the extension has almost reached the EoL :) .. I will keep it alive for the old shell versions
