### ISSUE TITLE
Please keep tagging releases

### ISSUE THREAD

**Issue by besser82** [kgshank/gse-refresh-wifi#9]
Hello,

I want to package your extension for Fedora and EPEL (Extension Packages for Enterprise Linux, like CentOS and RHEL).  Without proper release tags that is really difficult to track new version and all…

Cheers,
  Björn

**Comment by kgshank** [comment]
will do that with the next update, some changes are in queue

**Comment by rugk** [comment]
Any news? Is this still maintained?

**Comment by kgshank** [comment]
Yes, but no updates for now. New enhancements are welcome
